-- +goose Up
CREATE TABLE parents (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    email TEXT NOT NULL UNIQUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE students (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    parent_id BIGINT NOT NULL REFERENCES parents(id),
    name TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE trial_classes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    subject TEXT NOT NULL,
    starts_at TIMESTAMPTZ NOT NULL,
    capacity INTEGER NOT NULL DEFAULT 4 CHECK (capacity > 0),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE bookings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id BIGINT NOT NULL REFERENCES students(id),
    trial_class_id BIGINT NOT NULL REFERENCES trial_classes(id),
    status TEXT NOT NULL DEFAULT 'pending_payment'
        CHECK (status IN ('pending_payment', 'confirmed', 'payment_failed', 'cancelled')),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE payment_attempts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    booking_id BIGINT NOT NULL REFERENCES bookings(id),
    status TEXT NOT NULL
        CHECK (status IN ('pending', 'succeeded', 'failed')),
    provider_reference TEXT UNIQUE,
    failure_reason TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_students_parent_id
ON students (parent_id);

CREATE INDEX idx_bookings_trial_class_status
ON bookings (trial_class_id, status);

CREATE INDEX idx_bookings_student_class_status
ON bookings (student_id, trial_class_id, status);

CREATE INDEX idx_payment_attempts_booking_id
ON payment_attempts (booking_id);

CREATE UNIQUE INDEX uniq_confirmed_booking_per_student_class
ON bookings (student_id, trial_class_id)
WHERE status = 'confirmed';

-- +goose Down
DROP INDEX IF EXISTS uniq_confirmed_booking_per_student_class;
DROP TABLE IF EXISTS payment_attempts;
DROP TABLE IF EXISTS bookings;
DROP TABLE IF EXISTS trial_classes;
DROP TABLE IF EXISTS students;
DROP TABLE IF EXISTS parents;
